# Generated by Django 2.2.3 on 2019-07-13 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=18, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=18, verbose_name='密码')),
                ('email', models.CharField(default='', max_length=200, verbose_name='邮箱')),
                ('headImg_100x100', models.TextField(default='../static/images/defaultUserHead/default_userheag_img_100x100.png', verbose_name='用户头像 100x100')),
                ('headImg_48x48', models.TextField(default='../static/images/defaultUserHead/default_userheag_img_48x48.png', verbose_name='用户头像 48x48')),
                ('headImg_35x35', models.TextField(default='../static/images/defaultUserHead/default_userheag_img_35x35.png', verbose_name='用户头像 35x35')),
                ('chickenSoup', models.CharField(default='', max_length=20, verbose_name='鸡汤文')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.UserInfo')),
            ],
            options={
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.UserInfo')),
            ],
            options={
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='BookMarkClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserInfo')),
            ],
            options={
                'verbose_name_plural': '书签分类',
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BookMarkClassify')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.UserInfo')),
            ],
            options={
                'verbose_name_plural': '书签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('createTime', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('deleted', models.IntegerField(default=0, verbose_name='是否删除标识')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Classify', verbose_name='分类')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
    ]
