# Generated by Django 2.1.8 on 2019-05-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summery',
        ),
    ]
