# Generated by Django 2.1.8 on 2019-07-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190531_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': '书签',
            },
        ),
        migrations.CreateModel(
            name='BookMarkClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserInfo')),
            ],
            options={
                'verbose_name_plural': '书签分类',
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BookMarkClassify'),
        ),
    ]
